### PR TITLE
updated chinese translation

### PR DESCRIPTION
**Pull request by MarkChan0225**
idk if the way i commit is right, but hope i can commit to this project!. My discord: markchan0225

## Description

Updated translations.

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by SlayerOrnstein** [comment]
So the thing here and I blame myself is that we add translations using [crowdin](https://navis.t.warframestat.us/). But seeing that you translated a lot I'm not going to out right say no because I don't want you to just do the same thing.

So with that said any future translations should be done [here](https://navis.t.warframestat.us/)

**Comment by SlayerOrnstein** [comment]
Looking at it closely I see you're overriding somethings that have already been translated. I think at that point you should head over to https://navis.t.warframestat.us/ and do the translations there

**Comment by MarkChan0225** [comment]
It's ok, I think there are still some translations that should be edited. I will do it again.

**Comment by SlayerOrnstein** [comment]
Alright just saw your request. Welcome to the club and hope to see more of you in the discrod server, and also thank you

**Comment by MarkChan0225** [comment]
Thanks. I have just done all the translations :)

**Pull request closed without merging**
