### PR TITLE
fix(l10n): New translations

### PR DESCRIPTION
**Pull request by wfcd-bot-boi**

### CODE REVIEW

**Review by SlayerOrnstein — APPROVED** [review]

**Comment by SlayerOrnstein** [comment]
@TobiTenno I'm assuming that if someone adds translations this pull request will be updated with them right?

**Comment by TobiTenno** [comment]
Through crowding, yeah.

**Comment by SlayerOrnstein** [comment]
Alright just gonna leave it open in case someone translates stuff and then merge it for the v2.7.1 auto release.

**Pull request merged**
