### PR TITLE
feat(codex): display drop tables for items with `drops` key i.e relics (#160)

### LINKED ISSUE #160: [Feature] In the Codex, make Relics interactable to show where they drop and at which rate
### Is your feature request related to a problem?

The codex system you implemented in the app is fantastic. Searching for an item (example Strun Prime) provides which components it's made of, and tapping on those components shows where they drop.

In the case of prime components however, it only shows which relics drop them but not in which missions to obtain said relics.
And searching for the specific relic doesn't provide with any valuable information, just a blank page.

### Describe the feature you would like.

Being able to see where the Relics drop from, at which chance and what would be the most efficient way (e.g. do this mission until x rotation, extract, repeat), would be very useful and make the process of obtaining specific prime sets much easier. An app called [Lootr for Warframe](https://play.google.com/store/apps/details?id=com.ogg.technologies.warframerewards) works in a similar way.

UI wise, it would also be cool to be able to tap on relics inside the components pages to get redirected to the relic page for information on where the relic drops.

It might also be a good idea to unify the relic variants (intact, exceptional, flawless, radiant) into a single page. The variants could be shown similarly to how components are shown on craftable items, and tapping on them would redirect to information specific only to that variant (drop chances of the contained items).

### Additional context

Strun Prime > tap on barrel > list of relics with drop chances > tap on Axi N8 Intact > Axi N8 codex page with drop rates by mission and most efficient rotation strategy > tapping on the Intact icon in the Axi N8 page shows its contents with the items' rarities

### PR DESCRIPTION
**Pull request by SlayerOrnstein**
## Description

Follows the feature request for #160.
closes #160 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by TobiTenno** [comment]
@SlayerOrnstein should this be a draft?

**Comment by SlayerOrnstein** [comment]
Nah it's cool, I just haven't had much time this week

**Review by TobiTenno — APPROVED** [review]

**Comment by TobiTenno** [comment]
Screenshot_20220913-121754
No overview and market gives an unknown error
Screenshot_20220913-121854

**Comment by TobiTenno** [comment]
right, so i think we got this backwards, lol

if it has 'drops', that's where the item drops, not what the item drops, like like you'd expect for a relic. i'm working on integrating TitaniaProject's warframe-relic-data to be part of relics... i think that'll let you do what you're looking to do cleanly, but until then, you'd have to find all of an item's relics to find where they drop

**Comment by TobiTenno** [comment]
that said, what i'm seeing of the relics in the component list for drop chance is awesome so far

**Comment by SlayerOrnstein** [comment]
> right, so i think we got this backwards, lol
> 
> if it has 'drops', that's where the item drops, not what the item drops, like like you'd expect for a relic. i'm working on integrating TitaniaProject's warframe-relic-data to be part of relics... i think that'll let you do what you're looking to do cleanly, but until then, you'd have to find all of an item's relics to find where they drop

Yeah so the way it works is by doing a search and getting what's closely matching the location, basically a little regex. But yeah if the item is vaulted there won't be any drop locations.

As for market idk they keep changing the JSON so every once and awhile it'll break, it could be the name of the item not matching anything they have in their item to item URL thing.

**Comment by SlayerOrnstein** [comment]
Yeah market is gonna be a whole separate commit and fix because they way it works affects more then just relics.

**Pull request merged**
