### PR TITLE
UI Quality of Life

### PR DESCRIPTION
**Pull request by SlayerOrnstein**
### What did you fix? (provide a description or issue closes statement)
Simple UI quality of life. This UI change will clear things up for a few other features in the future.

See issue #113 

### TODO:
- [x] Change "void trader" to "Baro Ki' Teer".
- [x] Remove back space to open hamburger menu.

### Considerations
- Does this contain a new dependency? **Yes**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter? **Yes*
- Is is a bug fix, feature request, or enhancement? **Enhancement**

### CODE REVIEW

**Comment by SlayerOrnstein** [comment]
> do you want this as a draft or are you ok with me dissecting your code?

Perfectly okay with people looking thru it. 

Might even help with some of the color choosing.

**Comment by SlayerOrnstein** [comment]
I choose to not change any colors until Flutter has implemented Material 3, specifically dynamic colors.

**Comment by TobiTenno** [comment]
Not seeing any apks from the build 🤔

**Comment by SlayerOrnstein** [comment]
This next one should be outputting apks, let me know if it doesn't

**Comment by TobiTenno** [comment]
Ah, yup, I'm getting it now. I'm not a huge fan of both top and bottom nav, I feel like all the nave should be top or all bottom.

**Comment by SlayerOrnstein** [comment]
> Maybe a FAB for settings and discord and all bottom nav?

Shouldn't be using FAB for that.

> Ah, yup, I'm getting it now. I'm not a huge fan of both top and bottom nav, I feel like all the nave should be top or all bottom. 

It's more then likely just the height because it also feels off compared to what I've seen, also remember that tabs isn't always gonna be there.

**Comment by vanja-san** [comment]
Should I send sizes, colors, etc.? 🤓

**Comment by SlayerOrnstein** [comment]
No it's okay, for now I'm gonna let the framework decide the colors, as for size Flutter has a navigation bar height constant that I'll be using.

**Comment by TobiTenno** [comment]
This is probably asking a lot, but do you have a full list of the changes, by chance?

**Comment by SlayerOrnstein** [comment]
> This is probably asking a lot, but do you have a full list of the changes, by chance?

## Features:
- Removed the hamburger menu in favor of a navigation bar
- Revamped Baro ki'teer panal
- Moved Baro's card second from the top of the list
- Moved invasion construction progress to invasion tab
- Slimmed Darvo's daily sale to take up less space
- Dark theme is now darker 

## Fixes:
- Codex not filtering search results when choosing a filter
- More of the app now uses more consistent app styling to both Material guidelines and itself
- Bunch of internal bug fixing

## Performance:
- Cleaned up dependency loading, slightly faster start up (don't quote me on this)
- load local assets on start
- Performance based code refactoring in certain parts of the app

Off the top of my head I think that's all. After I dependency loading and removed Get_it I did notice a big improvement when first initializing the app on my Nexus 6P, have yet to try it on my new phone though.

**Review by TobiTenno — APPROVED** [review]

**Comment by TobiTenno** [comment]
Just some notes:
- first (post-fresh-install) load on both took about the same time for me
- new one looks nicer for sure, if darker and missing that nice blue
- both have the same odd state that they don't save where you were if you swipe back out of the app

**Comment by SlayerOrnstein** [comment]
- Yeah that's why I wasn't sure, because the 6P throttled a lot I couldn't properly measure.

- The blue is there but dark mode should have as much dark as primary as possible, it is still there in the light theme.

- Not a bug just something I never implemented. I can take care of that before I merge.

**Comment by TobiTenno** [comment]
Nah, don't worry about the last, put it on the next change, easier to track that way.

**Comment by SlayerOrnstein** [comment]
Understood

**Pull request merged**
