### PR TITLE
ci: fix missing SR plugins

### PR DESCRIPTION
**Pull request by TobiTenno**
## Description

add "extra plugins" config for release

example mirrored usage [here](https://github.com/WFCD/warframe-status/blob/main/.github/workflows/release.yml#L47-L52)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by SlayerOrnstein** [comment]
So I'm now just realizing the PR I made was on auto merge and it was only about half way done...

**Comment by TobiTenno** [comment]
ooof... sorry....

**Comment by TobiTenno** [comment]
well... continue from here, i guess? it didn't release anything, from what i'm seeing

**Comment by SlayerOrnstein** [comment]
It's no problem, my fault for not seeing it

**Review by SlayerOrnstein — APPROVED** [review]

**Pull request merged**
