### PR TITLE
Navis 2.0

### PR DESCRIPTION
**Pull request by SlayerOrnstein**
So this version aims to do two things. One is to rewrite the logic  and widgets to be as separate as possible while still being clean. The second thing is to refresh the UI, because I have no idea what I was doing initially and still sorta don't. I really just tried to adapt the website UI to work for mobile.

- [x] Rework folder architecture
- [x] Rework core features
- [x] Unified drop table, warframe-items, and riven data
- [x] Added SynthTargets outside of syndicates page
- [x] Rework notifications for localizations

### CODE REVIEW

**Comment by SlayerOrnstein** [comment]
Waiting for it for [NNBD support](https://github.com/dart-lang/language/issues/110) in Dart, preview state at the moment. So I probably won't be putting much into this update so I don't have a ton to change later, I will be taking some time to make small fixes to the current stable-ish branch and adding stuff to keep it locked on the pre NNBD sdk.

**Comment by TobiTenno** [comment]
yeah, i just worry that if someone else contributes (like me), they might forget and have some personal info exposed inadvertently

**Comment by SlayerOrnstein** [comment]
@TobiTenno I removed anything that might be specific to Android Studio and VS Code preference files, I'm going to do the same with the master branch.

**Comment by TobiTenno** [comment]
Nice

**Comment by SlayerOrnstein** [comment]
Done those files should not be tracked anymore, and apparently I am supposed to track the pubspec.lock so I took care of that one too.

**Comment by TobiTenno** [comment]
ah, interesting.

**Comment by SlayerOrnstein** [comment]
According to [this](https://dart.dev/guides/packages#upgrading-a-dependency) it seems so

**Comment by TobiTenno** [comment]
Makes sense, it's darts dependency lock filemfor consistent builds

**Comment by SlayerOrnstein** [comment]
Let me know if there's anything else the needs to be done to make it easier to contribute.

**Comment by TobiTenno** [comment]
I think once you have kinda where you want it on what you're working towards right now, and I'm more familiar with how things work right now, I'll probably be more able to help out

**Comment by SlayerOrnstein** [comment]
File structure wise, it's getting better and I feel that working with it is a lot easier then what I have in master

**Comment by TobiTenno** [comment]
Awesome! I look forward to it

**Pull request merged**
