### PR TITLE
feat: new explore page

### PR DESCRIPTION
**Pull request by SlayerOrnstein**
## Description
Create a new explore page with information on fish and to reintroduce maps *eventually*. This will also move the codex page over to the new explore page and make room for a personal inventory page #94

- [x] move codex
- [x] add fish information page

Will update comment with previews as I go

Codex:
https://github.com/WFCD/navis/assets/6075693/13c44b25-83bc-4e9a-9254-2c96c8d1cf0a

Fishing data:
https://github.com/WFCD/navis/assets/6075693/f3d9dc73-a23a-4701-9a08-2f3c54ddc35c

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by TobiTenno — APPROVED** [review]
I like the feature, but the border radius on the selection items for the codex are so close that they just make some dots on the sides

**Comment by SlayerOrnstein** [comment]
> I like the feature, but the border radius on the selection items for the codex are so close that they just make some dots on the sides



You mean this?

**Comment by TobiTenno** [comment]
@SlayerOrnstein from your video:

image

**Comment by TobiTenno** [comment]
feel free to merge when it works for you 🖖

**Review by TobiTenno — APPROVED** [review]

**Comment by SlayerOrnstein** [comment]
Maps are being annoying and it's gonna take me a fair bit to figure it out so I'm gonna push that part to a different PR, good news is I have a better idea of what I can do, bad news is that plotting coordinates is still bleh

**Pull request merged**
